---
- name: Apply configuration
  hosts: observed_servers 
  become: yes
  # vars:
  #  deployment_method: "native"

  tasks:
   - name: Include observed role ####!!!!!!!!!!!
     include_role:
      name: observed
    #  when: deployment_method == "native"
 