- name: Install prometheus-client
  pip:
   name: prometheus-client
   state: latest

- name: Copy server script
  copy:
   src: files/prometheus_server.py
   dest: /opt/prometheus_server.py
   mode: 0644

- name: Create service
  template:
   src: prometheus_server_service.j2
   dest: /etc/systemd/system/prometheus_server.service
   mode: 0644

# - name: Ensure firewall allows port 8080
#   ufw:
#    port: 8080
#    state: enabled
#    proto: tcp

- name: Enable and start service
  systemd:
   name: prometheus_server
   enabled: yes
   state: started
   daemon_reload: yes 