- name: Install prometheus-client
  pip:
   name: prometheus-client
   state: latest

- name: Copy server script
  copy:
   src: files/prometheus_server.py
   dest: /opt/zhirk/prometheus_server.py
   mode: 0644

- name: Copy Dockerfile
  copy:
   src: files/Dockerfile
   dest: /opt/zhirk/Dockerfile
   mode: 0644
  when: deployment_method == "container"

- name: Ensure Docker is running
  systemd:
   name: docker
   state: started
  when: deployment_method == "container"

- name: Check if Docker image exists
  command: docker images -q prometheus_server_container
  register: image_exists
  changed_when: false
  ignore_errors: true
  when: deployment_method == "container"

# docker_image:
  #  name: prometheus_server_container
  #  build:
  #   path: /opt/zhirk
  #   dockerfile: Dockerfile
  #  source: build
  #  state: present
  # when: deployment_method == "container"
- name: Build Docker image
  command:
   cmd: docker build -t prometheus_server_container -f /opt/zhirk/Dockerfile /opt/zhirk
  register: built_result
  # changed_when: "Successfully built' in built_result.stdout or 'Successfully tagged' in build_result.stdout"
  changed_when: built_result.rc == 0
  when: deployment_method == "container" and (image_exists.rc != 0 or image_exists.stdout == "")


- name: Create service
  template:
   src: prometheus_server_service.j2
   dest: /etc/systemd/system/prometheus_server.service
   mode: 0644

# - name: Ensure firewall allows port 8080
#   ufw:
#    port: 8080
#    state: enabled
#    proto: tcp

- name: Enable and start service
  systemd:
   name: prometheus_server
   enabled: yes
   state: started
   daemon_reload: yes 