- name: Copy Dockerfile
  copy:
   src: files/Dockerfile
   dest: /opt/zhirk/Dockerfile
   mode: 0644

# - name: Copy server script
#   copy:
#    src: ../observed/files/prometheus_server.py
#    dest: /opt/zhirk/prometheus_server.py
#    mode: 0644
######################################
- name: Build Docker image
  docker_image:
   name: prometheus_server_container
   build:
    path: /opt/zhirk
    dockerfile: Dockerfile
   source: build
   state: present